controllers:
  resource: ../src/Controller/
  type: attribute

login:
  path: /login
  controller: App\Controller\LoginController::login

register:
  path: /register
  controller: App\Controller\RegisterController::register
